### ISSUE TITLE
Replit banned this link i think.

### ISSUE THREAD

**Issue by EmiliaaKy** [User9684/stupid-discord-badge#1]
Could you possibly create another one thanks

**Comment by FailedWare37** [comment]
just fork the repo, it will be under your name if you fork it.

Update: it isnt banned, replit is just retarded.

**Comment by Manksien** [comment]
> just fork the repo, it will be under your name if you fork it.

didn't work

**Comment by FailedWare37** [comment]
@Manksien its a problem on replit's end I tried importing one of my own repos, it didnt work

**Comment by Dark102hola** [comment]
So sad

**Comment by Gtnx2** [comment]
even I just tried importing this and it didn't work

**Comment by FailedWare37** [comment]
@Gtnx2 its a problem on replit's side

**Comment by Iivid** [comment]
Do you think this'll be fixed later then?

> @Gtnx2 its a problem on replit's side

**Comment by FailedWare37** [comment]
> Do you think this'll be fixed later then?

I have no idea, worst case scenario is that it wont work for the rest of the day.

**Comment by Gtnx2** [comment]
@FailedWare37 oh ok thanks I was actually doing this for the Active Developer Badge for Discord and it didn't work so I tried another github and I put this one

**Comment by reepepefroggo** [comment]
You have to fork it and allow Replit access to your private github repos. (hyperlink under the space for inserting the repo's link)

**Comment by FailedWare37** [comment]
> You have to fork it and allow Replit access to your private github repos. (hyperlink under the space for inserting the repo's link)

I just did it, this works, thank you.

**Comment by EmiliaaKy** [comment]
> You have to fork it and allow Replit access to your private github repos. (hyperlink under the space for inserting the repo's link)

How to do it tho

**Comment by Gtnx2** [comment]
how do you fork it?

**Comment by FailedWare37** [comment]
> How to do it tho

Theres a little button under the place where you import the repo via link, click that.

**Comment by User9684** [comment]
Discord often likes to Ratelimit Replit's IP address, so it not working is only temporary and will likely work within a few hours.
Statement from Replit engineer:
![image](https://user-images.githubusercontent.com/65233836/201381801-22e8608e-a026-40bb-abfb-533c94fb69ce.png)

**Comment by Perchant76** [comment]
> how do you fork it?

![image](https://user-images.githubusercontent.com/63096336/201381799-69bc1b62-e00a-406c-a3d3-88f12a604e69.png)

**Comment by EmiliaaKy** [comment]
Thanks it worked

**Comment by Gtnx2** [comment]
It worked awesome!! thanks !

**Comment by JulyCrab** [comment]
I forked this repository made by another guy,but I don't have this box,is there any way to get it?
![image](https://user-images.githubusercontent.com/81880255/201383568-ad03d0b8-4eca-437d-869c-9db6ce7df51a.png)

**Comment by 002-sans** [comment]
> Statement from Replit engineer:

in the `shell` part, just write: `kill 1` and restart the bot.

**Comment by User9684** [comment]
> > Statement from Replit engineer:
> 
> in the `shell` part, just write: `kill 1` and restart the bot.

you can also just click `CTRL + D` or `CTRL + C` :p

**Comment by itskdhere** [comment]
> Discord often likes to Ratelimit Replit's IP address, so it not working is only temporary and will likely work within a few hours.
> Statement from Replit engineer:
> ![image](https://user-images.githubusercontent.com/65233836/201381801-22e8608e-a026-40bb-abfb-533c94fb69ce.png)
> 

It's **Cloudflare**, not Discord who rate-limits the repls. And all network trafic of Discord are Reverse-Proxied through Cloudflare.

Actually all repls are Containers (maybe Docker) which runs on Replit's VPS (each container with same IP address as of the VPS) which is on Google Cloud's Infrastructure.

Cloudflare rate-limits if 1000 logins are attempted within 24 hours, from same IP address.

**Comment by User9684** [comment]
> > Discord often likes to Ratelimit Replit's IP address, so it not working is only temporary and will likely work within a few hours.
> > Statement from Replit engineer:
> > ![image](https://user-images.githubusercontent.com/65233836/201381801-22e8608e-a026-40bb-abfb-533c94fb69ce.png)
> 
> It's **Cloudflare**, not Discord who rate-limits the repls. And all network trafic of Discord are Reverse-Proxied through Cloudflare.
> 
> Actually all repls are Containers (maybe Docker) which runs on Replit's VPS (each container with same IP address as of the VPS) which is on Google Cloud's Infrastructure.
> 
> Cloudflare rate-limits if 1000 logins are attempted within 24 hours, from same IP address.

Exactly. You need to wait awhile, or find a different host.

**Comment by 002-sans** [comment]
[![Deploy](https://replit.com/badge/github/User9684/stupid-discord-badge)](https://replit.com/github/User9684/stupid-discord-badge)
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://www.heroku.com/deploy/?template=https://github.com/User9684/stupid-discord-badge)
[![Deploy on Railway](https://railway.app/button.svg)](https://railway.app/new/template/NqJQfg?referralCode=27ekYT)

**Comment by SanityZeroPercent** [comment]
you don't have to run it on replit, just run it on your pc lmfao. 

all you need is nodejs and boom.

**Comment by itskdhere** [comment]
> you don't have to run it on replit, just run it on your pc lmfao. 
> 
> all you need is nodejs and boom.

Exactly..

**Comment by 002-sans** [comment]
> you don't have to run it on replit, just run it on your pc lmfao.
> 
> all you need is nodejs and boom.

simpler and faster for beginners who don't want to complicate things
