### ISSUE TITLE
Does it need to be done in replit ?

### ISSUE THREAD

**Issue by Frogyfucious** [User9684/stupid-discord-badge#10]
I have done it on my local pc cuz i got node installed. and everything wented ok, now im waiting for the badge

**Comment by 002-sans** [comment]
you don't have to do it on replit, it's just easier for those who don't have NodeJS or who are on mac

**Comment by DonaldTrumpz** [comment]
why would u need to do it in replit? use your brain

**Comment by User9684** [comment]
Nope, can be done on any host you want.
