### ISSUE TITLE
read this if you can't code

### ISSUE THREAD

**Issue by DonaldTrumpz** [User9684/stupid-discord-badge#13]
just stop... honestly stop

the point of this badge is for developers and you're just a wimply little skid looking for attention probably bragging to ur friends about how you got this cool badge and how it was so hard for you to fork a repo without understanding how to program yourself.

please just leave it to the REAL developers

edit: the badge wont even be considered cool because 90% of people who own it aren't developers

**Comment by theohemmer** [comment]
you literally have open-sourced a bot to spam peoples DMs, I personally prefer this one who doesn't cause any other hurt than peoples bragging to their friends

+ if there is no point getting this badge, there is no point telling peoples to stop wanting to have it, if you're a good programmer, your friends will just know it

**Comment by User9684** [comment]
> you literally have open-sourced a bot to spam peoples DMs

FUCKING CHAD LMFAO

**Comment by User9684** [comment]
"you're just a wimpy looking skid"

Aren't you the one who made a [Discord stealer?](https://github.com/DonaldTrumpz/Subliminal-Stealer) you honestly have no place to call anyone a skid.

**Comment by DonaldTrumpz** [comment]
> "you're just a wimpy looking skid"
> 
> Aren't you the one who made a [Discord stealer,](https://github.com/DonaldTrumpz/Subliminal-Stealer) and a [Mass DM Bot?](https://github.com/DonaldTrumpz/Discord-Friends-Mass-DM) You honestly have no place to call anyone a skid.

? the stealer isn't a "discord stealer", i wasn't even gonna implement it until someone mentioned it because discord accounts are worthless and they're only good for advertising

**Comment by DonaldTrumpz** [comment]
> you literally have open-sourced a bot to spam peoples DMs, I personally prefer this one who doesn't cause any other hurt than peoples bragging to their friends
> 
> + if there is no point getting this badge, there is no point telling peoples to stop wanting to have it, if you're a good programmer, your friends will just know it



> you literally have open-sourced a bot to spam peoples DMs, I personally prefer this one who doesn't cause any other hurt than peoples bragging to their friends
> 
> + if there is no point getting this badge, there is no point telling peoples to stop wanting to have it, if you're a good programmer, your friends will just know it

you're just contributing to the slow death of discord

**Comment by User9684** [comment]
> > "you're just a wimpy looking skid"
> > Aren't you the one who made a [Discord stealer,](https://github.com/DonaldTrumpz/Subliminal-Stealer) and a [Mass DM Bot?](https://github.com/DonaldTrumpz/Discord-Friends-Mass-DM) You honestly have no place to call anyone a skid.
> 
> ? the stealer isn't a "discord stealer", i wasn't even gonna implement it until someone mentioned it because discord accounts are worthless and they're only good for advertising

Idk man, still a stealer, still malware, so still cybercrime. Don't try to play off cybercrime by saying "it's not a discord stealer" because regardless, it is still malware.
