### ISSUE TITLE
why are you saying you hate discord

### ISSUE THREAD

**Issue by DonaldTrumpz** [User9684/stupid-discord-badge#14]
i mean you clearly dont, discord is one of the best things that could've happened to me and many others ;P stop talking shit on it

**Comment by ASOwnerYT** [comment]
I also hate discord

**Comment by OCsonic** [comment]
probably because element is better

**Comment by Xenorio** [comment]
I will talk shit on it then! Here's what's wrong with Discord:

- It's proprietary
- Massively violates GDPR
- Incompetent staff
- No privacy whatsoever, Discord can read all messages and listen in on all voice chats
- No actual customization options (that are ToS compliant)
- No selfhosting
- Filled with breaking bugs that have been ignored for years
- Will ban you for no reason whatsoever, then proceed to ghost you in support
- Uses Electron
- Keeps adding useless crap (like badges) instead of actually fixing their shit up
- Is not financially sustainable
- Constant breaking API changes **within the same version**
- Just generally crappy servers
- Will steal your guild from you if someone with enough money asks them to (See Stable Diffusion)
- Does not respect free speech (See Quackity)
- Ignores actual crimes happening on their platform

...and so much more!

**Comment by User9684** [comment]
> I will talk shit on it then! Here's what's wrong with Discord:
> 
> * It's proprietary
> * Massively violates GDPR
> * Incompetent staff
> * No privacy whatsoever, Discord can read all messages and listen in on all voice chats
> * No actual customization options (that are ToS compliant)
> * No selfhosting
> * Filled with breaking bugs that have been ignored for years
> * Will ban you for no reason whatsoever, then proceed to ghost you in support
> * Uses Electron
> * Keeps adding useless crap (like badges) instead of actually fixing their shit up
> * Is not financially sustainable
> * Constant breaking API changes **within the same version**
> * Just generally crappy servers
> * Will steal your guild from you if someone with enough money asks them to (See Stable Diffusion)
> * Does not respect free speech (See Quackity)
> * Ignores actual crimes happening on their platform
> * Does literally nothing in regards to all the account stealing going on
> 
> ...and so much more!

multiple of your points are wrong

**Comment by Xenorio** [comment]
> multiple of your points are wrong

I hope you are aware that just going "wrong lol" without listing what is wrong or why it's wrong does not provide any value whatsoever. Everything I have listed is either easily provable or literally happened to me.

**Comment by ASOwnerYT** [comment]
thx xenorio very good list I 100% agree.

electron is definitly the worst out of the list because it uses too much ram!!!!!1111111

**Comment by DonaldTrumpz** [comment]
> I will talk shit on it then! Here's what's wrong with Discord:
> 
> * It's proprietary
> * Massively violates GDPR
> * Incompetent staff
> * No privacy whatsoever, Discord can read all messages and listen in on all voice chats
> * No actual customization options (that are ToS compliant)
> * No selfhosting
> * Filled with breaking bugs that have been ignored for years
> * Will ban you for no reason whatsoever, then proceed to ghost you in support
> * Uses Electron
> * Keeps adding useless crap (like badges) instead of actually fixing their shit up
> * Is not financially sustainable
> * Constant breaking API changes **within the same version**
> * Just generally crappy servers
> * Will steal your guild from you if someone with enough money asks them to (See Stable Diffusion)
> * Does not respect free speech (See Quackity)
> * Ignores actual crimes happening on their platform
> * Does literally nothing in regards to all the account stealing going on
> 
> ...and so much more!

half of these are just based on one occasion and the rest are the same on every popular app; also wdym by "No privacy whatsoever, Discord can read all messages and listen in on all voice chats", that's literally how the internet works? how can they load messages on the client-side if they aren't stored????

**Comment by Xenorio** [comment]
> half of these are just based on one occasion and the rest are the same on every popular app

Believe it or not, a bunch of separate crappy stuff is still a bunch of crappy stuff. Which just keeps on coming with Discord. And just because the most popular communication platforms are all crappy does not mean Discord is great, it means it's as crappy as the others. There are places without any of these problems, look at anything on the Matrix protocol for example.

> that's literally how the internet works? how can they load messages on the client-side if they aren't stored????

https://en.wikipedia.org/wiki/End-to-end_encryption

**Comment by User9684** [comment]
> > multiple of your points are wrong
> 
> I hope you are aware that just going "wrong lol" without listing what is wrong or why it's wrong does not provide any value whatsoever. Everything I have listed is either easily provable or literally happened to me.

I am aware, I just simply didn't care enough to write out a list for each item that I believe is wrong and with a reason. Just know that Discord *is* internally trying to crack down on account stealing, phishing, etc. Saying they "don't care" and "aren't trying to fix it" is blatantly wrong.

**Comment by Xenorio** [comment]
> Just know that Discord is internally trying to crack down on account stealing, phishing, etc.

Ah yes, because storing auth tokens in plain text and having a goddamn QR code bypass 2FA is very much trying their best. Just going around banning people does not help anyone.

**Comment by User9684** [comment]
> > Just know that Discord is internally trying to crack down on account stealing, phishing, etc.
> 
> Ah yes, because storing auth tokens in plain text and having a goddamn QR code bypass 2FA is very much trying their best. Just going around banning people does not help anyone.

Auth tokens aren't stored in plain text anymore? Malware has to inject itself into the Discord JS files to grab victims tokens.

"Just going around banning people does not help anyone." 
Ah, so actively taking down the servers that spread QR scams doesn't help anyone? What do you want Discord to do? Disable different IP QR Logins? That breaks VPNs. Disable multi region QR logins? Lots of ISPs show your region in different areas.
Discord is doing what they can by suspending the guilds that use QR to steal accounts.

**Comment by Xenorio** [comment]
> Auth tokens aren't stored in plain text anymore?

They are, just checked, gotta run a regex over some leveldb files and Bob's your uncle

> Ah, so actively taking down the servers that spread QR scams doesn't help anyone?

Not in a system where you can create thousands of new ones each second if you wanted to. Getting banned is just a minor annoyance there, not on mission abort level. 

>  What do you want Discord to do?

Oh i don't know, maybe don't have QR bypass 2FA? And, i know, weird idea, separate tokens for each session? Maybe even the option to disable QR logins altogether on your account?

**Comment by User9684** [comment]
> Oh i don't know, maybe don't have QR bypass 2FA? And, i know, weird idea, separate tokens for each session? Maybe even the option to disable QR logins altogether on your account?

Each session does have its on auth token...
And auth tokens inside the ldb files are encrypted now, thats why stuff such as bbystealer and piratestealer inject into the client rather than reading those files anymore.

**Comment by Xenorio** [comment]
> Each session does have its on auth token...

Nope, each account has its own "master" token, which can only be changed by resetting the password

> And auth tokens inside the ldb files are encrypted now

Again, I literally just checked, they are not. Using the latest stable version on Linux.
