### ISSUE TITLE
unexpected token .

### ISSUE THREAD

**Issue by Perchant76** [User9684/stupid-discord-badge#2]
`/home/ubuntu/stupid-discord-badge/index.js:17
        if (interaction?.data?.name === 'lol') {
                        ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)`

I'm running it on my ubuntu server installed npm. Any fix?

**Comment by User9684** [comment]
How are you running it?

**Comment by Perchant76** [comment]
sudo npm run run < token>

**Comment by User9684** [comment]
This doesn't seem to happen for anyone else, are you actually putting < token> or do you replace it with just the token like shown in the example?

**Comment by Perchant76** [comment]
`npm run run akgdfgjsdfôgksfjgôlsdkjgôsdflkgjdsgôlkjsdfôgihepoihsddgf`
i do it like this without <>

**Comment by User9684** [comment]
alright, are you using the most recent node version..?

**Comment by Perchant76** [comment]
v10.19.0

**Comment by User9684** [comment]
hmm, very odd. Could you try deleting your folder and do `git clone https://github.com/User9684/stupid-discord-badge.git` to re-pull it?

**Comment by Perchant76** [comment]
Tried nothing changed

**Comment by User9684** [comment]
hmmm, very odd.

**Comment by User9684** [comment]
Try running `npm i`?

**Comment by User9684** [comment]
Try updating to node version 17 aswell, from what I've seen it's caused by older versions of node.

**Comment by User9684** [comment]
```
sudo apt update
curl -sL https://deb.nodesource.com/setup_17.x | sudo bash -
sudo apt install -y nodejs
node -v
```

**Comment by Perchant76** [comment]
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
source ~/.bashrc
nvm list-remote
nvm install v14.17.6
```
worked for me

**Comment by User9684** [comment]
Did the repo work with updated node?

**Comment by Perchant76** [comment]
Yes

**Comment by Perchant76** [comment]
Closing issue
