### ISSUE TITLE
Link is not wroking

### ISSUE THREAD

**Issue by karlrengav** [User9684/stupid-discord-badge#4]
The link to copy is not working

**Comment by User9684** [comment]
Are you sure you are pasting it in correctly?

**Comment by BrokenDetector** [comment]
Same problem . I think it's on the Repl side, not github

**Comment by Perchant76** [comment]
which link?

**Comment by karlrengav** [comment]
Ye, i'm pasting it correctly.

**Comment by FailedWare37** [comment]
You need to connect your github account to replit. 

Under the paste box where you put in the repo you want to import there's a little text saying to connect your github account, after that you can import the repo.

![image](https://user-images.githubusercontent.com/92532021/201415422-126ffade-4a4e-42c8-840e-c1311d6bbfbb.png)

**Comment by FaaZ002** [comment]
I connected my GitHub account but the link is still not working.

**Comment by User9684** [comment]
It's a repl issue, likely got ratelimited by github lol

**Comment by 002-sans** [comment]
it worked for me
