### ISSUE TITLE
"The application did not respond"

### ISSUE THREAD

**Issue by TheSubjectZero** [User9684/stupid-discord-badge#5]
Yeah so basically it says "The application did not respond" when i use /lol with my alt. I tried like 10 times.

![PgSoFmXl](https://user-images.githubusercontent.com/81418612/201387819-ccdb5b5f-9ba9-4ed1-ad9e-3b9954905475.png)

**Comment by wisecio** [comment]
Same here!

**Comment by wisecio** [comment]
> Yeah so basically it says "The application did not respond" when i use /lol with my alt. I tried like 10 times.
> 
> ![PgSoFmXl](https://user-images.githubusercontent.com/81418612/201387819-ccdb5b5f-9ba9-4ed1-ad9e-3b9954905475.png)

I ran the npm run run command again and instantly typed the /lol command and it worked.

**Comment by TheSubjectZero** [comment]
> > Yeah so basically it says "The application did not respond" when i use /lol with my alt. I tried like 10 times.
> > ![PgSoFmXl](https://user-images.githubusercontent.com/81418612/201387819-ccdb5b5f-9ba9-4ed1-ad9e-3b9954905475.png)
> 
> I ran the npm run run command again and instantly typed the /lol command and it worked.

Ah yes i just ran the command again and it worked. Im just stupid. Thanks for the help mate.
