### ISSUE TITLE
Bot invite link not showing

### ISSUE THREAD

**Issue by RennieSs** [User9684/stupid-discord-badge#6]
Am i the only one having problems with Replit?

When i run the code it says 
"up to date, audited 5 packages in 1s

found 0 vulnerabilities"

But the invitelink never shows up

**Comment by Perchant76** [comment]
what have you run?

**Comment by TheSubjectZero** [comment]
The first time i tried the same thing happened for me. To fix it i just created another one of this project thing and did the same thing.

**Comment by RennieSs** [comment]
npm run run [bot token here]

**Comment by RennieSs** [comment]
> The first time i tried the same thing happened for me. To fix it i just created another one of this project thing and did the same thing.

So i should yes create a new project?

**Comment by Perchant76** [comment]
> > The first time i tried the same thing happened for me. To fix it i just created another one of this project thing and did the same thing.
> 
> So i should yes create a new project?

yes

**Comment by RennieSs** [comment]
> 

omg it worked lmfao, tysm
