### ISSUE TITLE
Add alternative method using Node.js local installation?

### ISSUE THREAD

**Issue by blackma9ick** [User9684/stupid-discord-badge#7]
This.. masterpiece can be used without Replit.

One simply needs to:

1. install Node.js (with NPM built-in);
2. clone the repo;
3. run the `npm run run TOKEN` at the repo root;
4. BOUM! the URL will pop up. Now go on with NTTS.

I think this would be a very good alternative method to add in the `README`, considering Replit is literally dying right now.

Also :
Silly cat =3

**Comment by yogi701** [comment]
I'm getting this 
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by seriousm4x** [comment]
I created an alternative program heavily inspired by this repo in go to have zero runtime dependencies. No node, just download the release and run it.
https://github.com/seriousm4x/discord-developer-badge

**Comment by 002-sans** [comment]
> This.. masterpiece can be used without Replit.
> 
> One simply needs to:
> 
> 1. install Node.js (with NPM built-in);
> 2. clone the repo;
> 3. run the `npm run run TOKEN` at the repo root;
> 4. BOUM! the URL will pop up. Now go on with NTTS.
> 
> I think this would be a very good alternative method to add in the `README`, considering Replit is literally dying right now.
> 
> Also : Silly cat =3

nobody said that you have to use replit? in the README it says how to use the program to get the badge, not how to do on replit.

**Comment by blackma9ick** [comment]
> nobody said that you have to use replit? in the README it says how to use the program to get the badge, not how to do on replit.

I may have worded this issue poorly.
The README instructions are incomplete; you must also refer to the sidebar, which gives the Replit method.
This isn't very GitHub-style.

It would be preferable to put all the instructions in the README.

**Comment by User9684** [comment]
Done
