### ISSUE TITLE
unfortunate

### ISSUE THREAD

**Issue by 1x6** [User9684/stupid-discord-badge#9]
the problem is now dumb mfs who cant code at all can get the developer badge. kinda ruins the entire point. enjoy the free forks and stars tho i guess..

**Comment by theohemmer** [comment]
Always a cat and mouse game, Discord will set stronger restrictions to get the badge, bots will be developed to made this easier to have, all of that until the last guy who can have it is the MEE6 developer
At least I think a lot of people won't build the habit to do this every months
